### 20184645 김영찬
### 배열 생성 예

In [3]:
# NumPy 임포트
import numpy as np
# 1차원 배열
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr1) # 배열 출력
print(arr1[3]) # 4
print(arr1[3:6]) # 4,5,6
print(arr1.shape) # 배열 차원의 크기: (10,)
print(arr1.dtype) # 배열 요소의 자료형: int32


[ 1  2  3  4  5  6  7  8  9 10]
4
[4 5 6]
(10,)
int32


In [4]:
# 2차원 배열, 2 x 3 배열
arr2 = np.array([[1.0, 2.0, 3.0], [4.4, 5.5, 6.6]])
print(arr2) # 배열 출력
print(arr2[1]) # [4.4, 5.5, 6.6]
print(arr2[1, 2]) # 6.6
print(arr2[1][2]) # 6.6
print(arr2.shape) # (2,3)
print(arr2.dtype) # float64
print(arr2.ndim) # 차원(축)의 개수: 2
print(arr2.size) # 원소의 개수: 6

[[1.  2.  3. ]
 [4.4 5.5 6.6]]
[4.4 5.5 6.6]
6.6
6.6
(2, 3)
float64
2
6


In [5]:
# 3차원 배열, 2 x 3 x 4 배열
arr3 = np.array([[[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]],
                 [[11, 12, 13, 14],
                  [15, 16, 17, 18],
                  [19, 20, 21, 22]]])
print(arr3) # 배열 출력
print(arr3[0]) # 1행 출력
print(arr3[1, 2]) # 2행, 3열 출력
print(arr3[1, 2, 0]) # 19
print(arr3[1][2][0]) # 19
print(arr3.shape) # (2,3,4)
print(arr3.dtype) # int32
print(arr3.ndim) # 3
print(arr3.size ) # 24

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[11 12 13 14]
  [15 16 17 18]
  [19 20 21 22]]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[19 20 21 22]
19
19
(2, 3, 4)
int32
3
24
